AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "katobot the golden quotes by Kato-bucho"

Globals:
  Function:
    Timeout: 180

Parameters:
  MessengerUrl:
    Type: String
    Default: "input messenger webhook URL"
  DynamoDbTable:
    Type: String
    Default: "input DynamoDB table name"


Resources:
  KatobotIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "KatobotLambdaPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "ce:GetCostAndUsage"
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:Describe*"
                  - "dynamodb:List*"
                  - "dynamodb:GetItem"
                  - "dynamodb:Query"
                  - "dynamodb:Scan"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                Resource: "*"

  KatobotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: main.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:ap-northeast-1:531950576581:layer:requests:1
      Role: !GetAtt KatobotIamRole.Arn
      Environment:
        Variables:
          MESSENGER_URL: !Ref MessengerUrl
          TZ: Asia/Tokyo
          DYNAMODB_TABLE: !Ref DynamoDbTable
      Events:
        NotifytoMessenger:
          Type: Schedule
          Properties:
            Schedule: cron(55 23 ? * SUN-THU *)

  KatobotLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${KatobotFunction}
      RetentionInDays: 14

Outputs:
  KatobotFunction:
    Description: "Katobot"
    Value: !GetAtt KatobotFunction.Arn
  KatobotIamRole:
    Description: "Implicit IAM Role created for Katobot"
    Value: !GetAtt KatobotIamRole.Arn